[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "chm-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.38.23",
    "fastapi[standard]>=0.140.0",
    "geopandas>=1.1.3",
    "mapbox-vector-tile>=2.2.0",
    "mercantile>=1.2.1",
    "numpy>=2.2.6",
    "pillow>=11.3.0",
    "pmtiles>=3.5.0",
    "pydantic-settings>=2.11.0",
    "rasterio>=1.5.0",
    "requests>=2.32.5",
    "shapely>=2.1.1",
]

[tool.fastapi]
entrypoint = "app.main:app"

[tool.setuptools]
packages = ["app"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
